version: '3.2'
services:
  front:
    container_name: front
    build: ./reused-modules-front
    volumes:
      - ./reused-modules-front/:/app/
      - /app/node_modules
    command: pnpm dev
    ports:
      - '3001:3000'

  api:
    container_name: api
    build: ./reused-modules-api
    volumes:
      - ./reused-modules-api/:/app/
    ports:
      - '8080:8080'

  # graphql:
  #   container_name: graphql
  #   build: ./reused-modules-graphql
  #   volumes:
  #     - ./reused-modules-graphql/:/app/
  #   ports:
  #     - '8000:8000'

  cms:
    container_name: cms
    build: ./reused-modules-cms
    volumes:
      - ./reused-modules-cms/:/app/
      - /app/node_modules
    command: pnpm dev
    ports:
      - '3002:6000'

  db:
    container_name: db
    image: mysql:8
    volumes:
      - ./docker/db/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 33080:3306
